### ISSUE TITLE
Home Assistant Voice Install Failure

### ISSUE THREAD

**Issue by jarrah31** [m5stack/M5CoreS3-Esphome#15]
I've attempted to install Home Assistant Voice by following the guide found here: https://docs.m5stack.com/en/guide/homeassistant/m5cores3/m5cores3_quick_start

Within "3. Configuring the device", it asks you to include the following yaml to the configuration file:
```
packages:
  m5stack.cores3-voice-assistant: github://m5stack/M5CoreS3-Esphome/voice-assistant/m5stack-cores3.yaml@main
```
Having done that and pressed Save and then Install, during installation it gives the following error:
```
INFO ESPHome 2024.7.1
INFO Reading configuration /config/m5cores3-se.yaml...
INFO Updating https://github.com/m5stack/M5CoreS3-Esphome@None
WARNING GPIO35 is used by the PSRAM interface on ESP32-S3R8 / ESP32-S3R8V and should be avoided on these models
Failed config

ota.esphome: [source /config/.esphome/packages/54af47dc/voice-assistant/m5stack-cores3.yaml:80]
  
  Found multiple configurations but password is inconsistent.
  platform: esphome
  password: <YOUR_OTA_KEY>
  version: 2
  port: 3232
```
This is because the file it references looks like this: https://github.com/m5stack/M5CoreS3-Esphome/blob/b955eed7436b4ca43344a51307759ba12f39b669/voice-assistant/m5stack-cores3.yaml#L82

Given that the instructions ask you to specify a remote packages file that I can't edit, is this method broken? I could copy all the yaml file contents and paste into my local file, but doesn't that defeat the purpose of using remote packages?

My basic config file looks like this:
```
esphome:
  name: m5cores3-se
  friendly_name: M5CoreS3 SE

packages:
  m5stack.cores3-voice-assistant: github://m5stack/M5CoreS3-Esphome/voice-assistant/m5stack-cores3.yaml@main

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "removed"

ota:
  - platform: esphome
    password: "removed"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Cores3-Se Fallback Hotspot"
    password: "removed"

captive_portal:
```
