### ISSUE TITLE
How to use with ESPhome

### ISSUE THREAD

**Issue by vaski666** [m5stack/M5CoreS3-Esphome#7]
would it be possible to give instructions on how to use this respository in Esphome to add CoreS3 support to Esphome?

**Comment by vaski666** [comment]
Seems to have found the answer by browsing the files.
this should be added to the code 
```
external_components:
  - source:
      type: git
      url: https://github.com/m5stack/M5CoreS3-Esphome
    components: [ board_m5cores3, m5cores3_audio, m5cores3_display ]
    refresh: 0s

```
